### PR TITLE
electron: Increase the timeout for the first launch

### PR DESCRIPTION
**Pull request by danigm**
https://phabricator.endlessm.com/T32261

### CODE REVIEW

**Review by dylanmccall — COMMENTED** [review]
Makes sense to me. But just before we merge it, I'm wondering, is it feasible to do this copy operation in the Electron app so we can start counting when it is finished? (Rather than guessing at how long it will be). We do have a JavaScript implementation of `getEndlessKeyDrive`, now, so moving that file copy operation to the Electron application might give us a path to remove a lot of Endless Key-specific code from the Python application. But if that sounds like too much stuff to shift around, I totally understand :)

**Comment by danigm** [comment]
> Makes sense to me. But just before we merge it, I'm wondering, is it feasible to do this copy operation in the Electron app so we can start counting when it is finished? (Rather than guessing at how long it will be). We do have a JavaScript implementation of `getEndlessKeyDrive`, now, so moving that file copy operation to the Electron application might give us a path to remove a lot of Endless Key-specific code from the Python application. But if that sounds like too much stuff to shift around, I totally understand :)

Yes, good idea, let's do that and we can keep the python code simpler and we'll have more control over the loading steps in the frontend, so in the future we can show more detailed information in the loading screen.

**Comment by danigm** [comment]
I've added a new commit to the PR, I've moved all the code that calculates the environment variables and creates the home to the kolibri-electron.

**Comment by erikos** [comment]
> I've added a new commit to the PR, I've moved all the code that calculates the environment variables and creates the home to the kolibri-electron.

Excellent - let's see if Dylan likes that now :)

**Comment by dylanmccall** [comment]
Yay! Just what I always dreamed of. Thank you, @danigm :) I spotted an unrelated issue while testing it (https://phabricator.endlessm.com/T32333). Otherwise seems to be doing the trick.

**Pull request merged**
