### PR TITLE
Rename welcomeScreen to loadingScreen

### PR DESCRIPTION
**Pull request by manuq**
And start Kolibri right ahead.

Also remove unused imports.

Helps https://github.com/endlessm/kolibri-explore-plugin/issues/748

### CODE REVIEW

**Comment by dbnicholson** [comment]
Marking this as a draft so it's not merged until an explore plugin release is made with these changes.

**Review by dbnicholson — CHANGES_REQUESTED** [review]
The github build is pinned to `kolibri-explore-plugin~=6.0`, so that will have to be updated to `~=7.0`.

**Comment by manuq** [comment]
> The github build is pinned to `kolibri-explore-plugin~=6.0`, so that will have to be updated to `~=7.0`.

Good catch! Done

**Comment by starnight** [comment]
Err!  Looks like `pip install kolibri-explore-plugin~=7.0` cannot install the RC version directly:
```
ERROR: Could not find a version that satisfies the requirement kolibri-explore-plugin~=7.0 (from versions: 0.0.1, .., 6.47.0)
ERROR: No matching distribution found for kolibri-explore-plugin~=7.0
```
https://github.com/endlessm/endless-key-app/actions/runs/6235428040/job/16924622446?pr=156#step:12:12

**Comment by dbnicholson** [comment]
> Err! Looks like `pip install kolibri-explore-plugin~=7.0` cannot install the RC version directly:

For a release candidate, you have to specifically include the `rc` in the version specifier since `pip` otherwise ignores pre-releases:

```
$ pip install 'kolibri_explore_plugin~=7.0rc3'
Collecting kolibri_explore_plugin~=7.0rc3
  Downloading kolibri_explore_plugin-7.0.0rc3-py3-none-any.whl (24.6 MB)
     |████████████████████████████████| 24.6 MB 31.7 MB/s 
Installing collected packages: kolibri-explore-plugin
Successfully installed kolibri-explore-plugin-7.0.0rc3
```

**Review by dbnicholson — APPROVED** [review]
7.0.0 is released now, so I think this is ready to go in now. @starnight can you have a quick look?

**Review by starnight — APPROVED** [review]
LGTM!  Thanks!

**Pull request merged**
