### PR TITLE
APPX: Bump TargetDeviceFamily's MinVersion to 10.0.17763.0

### PR DESCRIPTION
**Pull request by starnight**
Sync the TargetDeviceFamily's MinVersion with the appxmanifest.xml generated from Visual Studio 2022.

https://phabricator.endlessm.com/T34622

### CODE REVIEW

**Comment by wjt** [comment]
Did you research what this means in terms of minimum Windows version, and what we expect this to fix?

I googled

**Comment by wjt** [comment]
...this version number and it seems to correspond to a 2018 update to Windows 10. https://en.m.wikipedia.org/wiki/Windows_10,_version_1809

It's probably OK to require that 4½-year-old version, but it's not clear from the commit message or ticket what problem this will solve.

**Comment by starnight** [comment]
I think it will not fix any thing.  But, I think we should sync with the output from Visual Studio to avoid unexpected things.

**Comment by wjt** [comment]
Is there any data on what % of Windows users have at least this version?

**Comment by starnight** [comment]
Err!  I found a Windows support life time list for each version. 
 https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions
Looks like even Windows 10 version 1507 with Build number 10240 will be supported to 2025-10-14.

Ok!  I change my mind.  This PR is optional, not mandatory.

**Pull request closed without merging**
