### PR TITLE
CI: Update the self-sign key for local test

### PR DESCRIPTION
**Pull request by starnight**
The original self-sign key is out of date. Generate a new key having 99 years validated time with PowerShell command on Windows:

New-SelfSignedCertificate `
  -Type Custom `
  -Subject "CN=4B001A25-B854-44D9-BAD3-8AD7FC7A8761" `
  -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}") `
  -KeyUsage DigitalSignature `
  -KeyAlgorithm RSA `
  -KeyLength 2048 `
  -FriendlyName "EOSFselfsign" `
  -CertStoreLocation "Cert:\CurrentUser\My" `
  -NotAfter (Get-Date).AddYears(99)

* The "CN" of Subject is the Publisher: Endless OS Foundation's ID on Microsoft store
* TextExtension is Extended Key Usage. The value represents self-signing certificate. Please see the document "Create a certificate for package signing" [1]

Then, export the key as selfsign.pfx from the CertStore by command:

$password = ConvertTo-SecureString `
  -String <password defined on GitHub CI "secrets.SELFSIGN_PHRASE"> `
  -Force `
  -AsPlainText
Export-PfxCertificate `
  -cert "Cert:\CurrentUser\My\<the Thumbprint of the key>" `
  -FilePath <export path of selfsign.pfx> `
  -Password $password

[1]: https://learn.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing#use-new-selfsignedcertificate-to-create-a-certificate

https://phabricator.endlessm.com/T34816

### CODE REVIEW

**Review by wjt — CHANGES_REQUESTED** [review]
Rather than putting the script to run into the commit message, please commit it as e.g. `build_winapp/UpdateSelfSignedCertificate.ps1`.

**Comment by starnight** [comment]
But, the Thumbprint of the key is shown after the key is generated.  And, we need the Thumbprint to export the key from CertStore.

**Comment by starnight** [comment]
Um ... I found https://tommymaynard.com/create-self-signed-certificate-and-export/
Maybe, it is doable.

**Comment by wjt** [comment]
OK, I see. In that case: why not place those instructions into `build_winapp/README.md`? My point is that we should make them as easy to find as the certificate itself, rather than having to dig through the commit history.

**Comment by starnight** [comment]
Let me think twice on next working day.  I'll test the example in https://github.com/endlessm/endless-key-app/pull/109#issuecomment-1545509727

**Comment by dbnicholson** [comment]
> But, the Thumbprint of the key is shown after the key is generated. And, we need the Thumbprint to export the key from CertStore.

Just FYI, apparently [a PFX file is just a PKCS12 file](https://en.wikipedia.org/wiki/X.509#Certificate_filename_extensions). In other words, it's just a container for an X.509 certificate and private key. We could do this all with openssl and not have to mess with certstore. Apparently "thumbprint" is also just Microsoft for fingerprint. However, since I don't have the passphrase for the existing PFX file, I can't really inspect it to see what's in the certificate.

**Comment by wjt** [comment]
I'll send you what I believe to be the passphrase privately.

**Review by wjt — APPROVED** [review]

**Comment by starnight** [comment]
Thanks for the approve.  And, the CI builds successfully, including signing the package with the self-signed key.  So, I merge this PR.

**Pull request merged**
